### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [mingelz/my-mac-env#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`setup.md`](https://github.com/mingelz/my-mac-env/blob/f9553e05bfd37e950557f5e5c4f08a31e25bc477/setup.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by mingelz** [comment]
Thank you. I have updated the link just now.
